name: Test Suite

on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.19.0"
      - run: go test ./... -cover
